import '../models/venue_model.dart';

// This temporary list provides the data required to populate the cards for the
// listings screen.  For testing purposes only.
// Remove once data is fed from Firestore
List<VenueClass> listingCardList = <VenueClass>[
  VenueClass(
      venueID: "LV0001",
      venueName: "The Piano Bar",
      venueArea: "The Strip",
      venueLocation: "Harrah's",
      venueAddress1: "3475 Las Vegas Blvd S",
      venueAddress2: "",
      venueDistrict: "The Strip",
      venueCity: "Las Vegas",
      venuePostCode: "89109",
      venueDirections:
          " On your left, Immediately inside the Carnaval  Court entrance",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/pianobarharrahs.png",
      venueRegPrice: 3,
      venueHHPrice: 2,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "18:00",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "18:00",
      venueCloseMonday1: "15:00",
      venueCloseMonday2: "02:00",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "15:00",
      venueCloseSunday2: "02:00",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "00:00",
      venueHHStartMonday2: "17:00",
      venueHHStartTuesday1: "01:00",
      venueHHStartTuesday2: "13:00",
      venueHHStartWednesday1: "02:00",
      venueHHStartWednesday2: "14:00",
      venueHHStartThursday1: "03:00",
      venueHHStartThursday2: "15:00",
      venueHHStartFriday1: "04:00",
      venueHHStartFriday2: "16:00",
      venueHHStartSaturday1: "05:00",
      venueHHStartSaturday2: "17:00",
      venueHHStartSunday1: "06:00",
      venueHHStartSunday2: "18:00",
      venueHHEndMonday1: "02:00",
      venueHHEndMonday2: "16:00",
      venueHHEndTuesday1: "03:00",
      venueHHEndTuesday2: "19:00",
      venueHHEndWednesday1: "04:00",
      venueHHEndWednesday2: "20:00",
      venueHHEndThursday1: "05:00",
      venueHHEndThursday2: "21:00",
      venueHHEndFriday1: "06:00",
      venueHHEndFriday2: "22:00",
      venueHHEndSaturday1: "07:00",
      venueHHEndSaturday2: "23:00",
      venueHHEndSunday1: "08:00",
      venueHHEndSunday2: "02:00",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0002",
      venueName: "JammyLand",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueAddress1: "1121 S Main St",
      venueAddress2: "",
      venueDistrict: "The Arts District",
      venueCity: "Las Vegas",
      venuePostCode: "89104",
      venueDirections: "",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/jammyland.png",
      venueRegPrice: 2,
      venueHHPrice: 1,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "00:00",
      venueHHStartMonday2: "17:00",
      venueHHStartTuesday1: "01:00",
      venueHHStartTuesday2: "13:00",
      venueHHStartWednesday1: "02:00",
      venueHHStartWednesday2: "14:00",
      venueHHStartThursday1: "03:00",
      venueHHStartThursday2: "15:00",
      venueHHStartFriday1: "04:00",
      venueHHStartFriday2: "16:00",
      venueHHStartSaturday1: "05:00",
      venueHHStartSaturday2: "17:00",
      venueHHStartSunday1: "06:00",
      venueHHStartSunday2: "18:00",
      venueHHEndMonday1: "02:00",
      venueHHEndMonday2: "16:00",
      venueHHEndTuesday1: "03:00",
      venueHHEndTuesday2: "19:00",
      venueHHEndWednesday1: "04:00",
      venueHHEndWednesday2: "20:00",
      venueHHEndThursday1: "05:00",
      venueHHEndThursday2: "21:00",
      venueHHEndFriday1: "06:00",
      venueHHEndFriday2: "22:00",
      venueHHEndSaturday1: "07:00",
      venueHHEndSaturday2: "23:00",
      venueHHEndSunday1: "08:00",
      venueHHEndSunday2: "02:00",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0003",
      venueName: "The Commonwealth",
      venueArea: "Downtown",
      venueLocation: "Fremont East",
      venueAddress1: "525 Fremont St",
      venueAddress2: "",
      venueDistrict: "Fremont East",
      venueCity: "Las Vegas",
      venuePostCode: "89101",
      venueDirections: "",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/commonwealth.png",
      venueRegPrice: 2,
      venueHHPrice: 3,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "00:00",
      venueHHStartMonday2: "17:00",
      venueHHStartTuesday1: "01:00",
      venueHHStartTuesday2: "13:00",
      venueHHStartWednesday1: "02:00",
      venueHHStartWednesday2: "14:00",
      venueHHStartThursday1: "03:00",
      venueHHStartThursday2: "15:00",
      venueHHStartFriday1: "04:00",
      venueHHStartFriday2: "16:00",
      venueHHStartSaturday1: "05:00",
      venueHHStartSaturday2: "17:00",
      venueHHStartSunday1: "06:00",
      venueHHStartSunday2: "18:00",
      venueHHEndMonday1: "02:00",
      venueHHEndMonday2: "16:00",
      venueHHEndTuesday1: "03:00",
      venueHHEndTuesday2: "19:00",
      venueHHEndWednesday1: "04:00",
      venueHHEndWednesday2: "20:00",
      venueHHEndThursday1: "05:00",
      venueHHEndThursday2: "21:00",
      venueHHEndFriday1: "06:00",
      venueHHEndFriday2: "22:00",
      venueHHEndSaturday1: "07:00",
      venueHHEndSaturday2: "23:00",
      venueHHEndSunday1: "08:00",
      venueHHEndSunday2: "02:00",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0004",
      venueName: "Velveteen Rabit",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueAddress1: "1218 S Main St",
      venueAddress2: "",
      venueDistrict: "The Arts District",
      venueCity: "Las Vegas",
      venuePostCode: "89104",
      venueDirections: "",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/velveteenrabbit.png",
      venueRegPrice: 3,
      venueHHPrice: 3,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "16:00",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "16:00",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "16:00",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "16:00",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "15:00",
      venueCloseMonday2: "02:00",
      venueCloseTuesday1: "15:00",
      venueCloseTuesday2: "02:00",
      venueCloseWednesday1: "15:00",
      venueCloseWednesday2: "02:00",
      venueCloseThursday1: "15:00",
      venueCloseThursday2: "02:00",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0005",
      venueName: "Miller's Alehouse",
      venueArea: "Town Square",
      venueLocation: "Town Square",
      venueAddress1: "6683 Las Vegas Blvd S",
      venueAddress2: "",
      venueDistrict: "Town Square",
      venueCity: "Las Vegas",
      venuePostCode: "89119",
      venueDirections: "Opposite Staples, at the front of Town Square",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/millersalehouse.png",
      venueRegPrice: 2,
      venueHHPrice: 2,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0006",
      venueName: "Frankie's Tiki Room",
      venueArea: "West of Strip",
      venueLocation: "W Charlston Blv",
      venueAddress1: "1712 W Charleston Blvd",
      venueAddress2: "",
      venueDistrict: "W Charlston Blv",
      venueCity: "Las Vegas",
      venuePostCode: "89102",
      venueDirections:
          "Centrally located near the Strip and two blocks west of the I-15 freeway",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/frankiestikiroom.png",
      venueRegPrice: 3,
      venueHHPrice: 2,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0007",
      venueName: "The Nerd Bar",
      venueArea: "Downtown",
      venueLocation: "Neonopolis",
      venueAddress1: "450 Fremont St #250",
      venueAddress2: "",
      venueDistrict: "Downtown",
      venueCity: "Las Vegas",
      venuePostCode: "89101",
      venueDirections:
          "Go up the escalator and the entrance is directly opposite",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/nerdbar.png",
      venueRegPrice: 3,
      venueHHPrice: 1,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0008",
      venueName: "The Barbershop",
      venueArea: "The Strip",
      venueLocation: "Cosmopolitan",
      venueAddress1: "Level 1, Boulevard Tower",
      venueAddress2: "3708 Las Vegas Blvd S",
      venueDistrict: "The Strip",
      venueCity: "Las Vegas",
      venuePostCode: "89109",
      venueDirections: "",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/barbershop.png",
      venueRegPrice: 4,
      venueHHPrice: 3,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0009",
      venueName: "Winchell's Pub & Grill",
      venueArea: "South of Strip",
      venueLocation: "The Park At Warm Springs",
      venueAddress1: "199 E Warm Springs Rd",
      venueAddress2: "",
      venueDistrict: "Paradise Valley",
      venueCity: "Las Vegas",
      venuePostCode: "89119",
      venueDirections: "On the corner of E Warm Springs Rd and Gilespie St",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/winchellspubandgrill.png",
      venueRegPrice: 2,
      venueHHPrice: 1,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0010",
      venueName: "The Front Yard",
      venueArea: "East of Strip",
      venueLocation: "Ellis Island",
      venueAddress1: "4178 Koval Ln",
      venueAddress2: "",
      venueDistrict: "East of Strip",
      venueCity: "Las Vegas",
      venuePostCode: "89109",
      venueDirections: "Directly behind Bally's",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/frontyard.png",
      venueRegPrice: 1,
      venueHHPrice: 1,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0011",
      venueName: "ReBar",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueAddress1: "1225 S Main St",
      venueAddress2: "",
      venueDistrict: "The Arts District",
      venueCity: " Las Vegas",
      venuePostCode: "89104",
      venueDirections: "",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/rebar.png",
      venueRegPrice: 4,
      venueHHPrice: 2,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
  VenueClass(
      venueID: "LV0012",
      venueName: "Pin-ups Bar",
      venueArea: "North of Strip",
      venueLocation: "Cannery Casino",
      venueAddress1: "2121 E Craig Rd",
      venueAddress2: "",
      venueDistrict: "North Las Vegas",
      venueCity: "Las Vegas",
      venuePostCode: "89030",
      venueDirections: "In the center of the casino floor",
      venueDescription:
          "pasngpj apjgn -angpijnsfdpn sapgjn apsjng  padsjnpnasg pjn pasjng pjangpjasgpija srrgh pasgp ahrg pjnargojn arougpwa 9g pajrgnorsbuaerg p9ua ergu b a0urb p9gpgbpargpbur pabrg oarugb paubgpbrabrgpaeb 9puh",
      venueImage: "assets/pinups.png",
      venueRegPrice: 4,
      venueHHPrice: 3,
      venueInOut: "1",
      venueInOutNote:
          "Main bar is indoors, where the entertainment is, but there is also a strip-side patio where you can also get a good view of what is happening inside.",
      venueViews: "2",
      venueViewsNote: "the patio is good for people watching",
      venueFood: "2",
      venueFoodNote: "Small bar snack menu available up until 10pm",
      venueSmoking: "1",
      venueSmokingNote:
          "Smoking is permitted throughout but is very well ventilated.",
      venueRecMusic: "2",
      venueRecMusicNote:
          "Recorded music is played between live entertainment acts",
      venueLiveEnt: "1",
      venueLiveEntNote:
          "Big Elvis performs on Tuesday, Wednesday and Friday afternoons. Karaoke 6-9pm every evening, followed by duelling pianos show.",
      venueCCharge: "1",
      venueCChargeNote: "Always free entry.",
      venueDressCode: "2",
      venueDressCodeNote:
          "The official code is no sportswear or beachwear after 6pm. Casual attire is the norm",
      venueChildPolicy: "3",
      venueChildPolicyNote: "21+ only",
      venueAccessibility: "2",
      venueAccessibilityNote:
          "Wheelchairs might find it difficult to access the patio from the the indoor bar",
      venueDistance: "0.43",
      venueGoodForTitle1: "Party vibe",
      venueGoodForDescription1: "Party vibe Description",
      venueGoodForTitle2: "All ages over 21",
      venueGoodForDescription2: "All ages over 21 Description",
      venueGoodForTitle3: "Duelling pianos show",
      venueGoodForDescription3: "Duelling pianos show Description",
      venueGoodForTitle4: "Karaoke early evening",
      venueGoodForDescription4: "Karaoke early evening Description",
      venueGoodForTitle5: "Meeting new people",
      venueGoodForDescription5: "Meeting new people Description",
      venueGoodForTitle6: "Patio",
      venueGoodForDescription6: "Patio Description",
      venueOpenMonday1: "11:00",
      venueOpenMonday2: "",
      venueOpenTuesday1: "11:00",
      venueOpenTuesday2: "",
      venueOpenWednesday1: "11:00",
      venueOpenWednesday2: "",
      venueOpenThursday1: "11:00",
      venueOpenThursday2: "",
      venueOpenFriday1: "10:00",
      venueOpenFriday2: "",
      venueOpenSaturday1: "10:00",
      venueOpenSaturday2: "",
      venueOpenSunday1: "10:00",
      venueOpenSunday2: "",
      venueCloseMonday1: "02:00",
      venueCloseMonday2: "",
      venueCloseTuesday1: "02:00",
      venueCloseTuesday2: "",
      venueCloseWednesday1: "02:00",
      venueCloseWednesday2: "",
      venueCloseThursday1: "03:00",
      venueCloseThursday2: "",
      venueCloseFriday1: "03:00",
      venueCloseFriday2: "",
      venueCloseSaturday1: "03:00",
      venueCloseSaturday2: "",
      venueCloseSunday1: "02:00",
      venueCloseSunday2: "",
      venueOpeningTimesNotes:
          "Opening times subject to change without warning due to Coronavirus",
      venueHHStartMonday1: "",
      venueHHStartMonday2: "",
      venueHHStartTuesday1: "",
      venueHHStartTuesday2: "",
      venueHHStartWednesday1: "",
      venueHHStartWednesday2: "",
      venueHHStartThursday1: "",
      venueHHStartThursday2: "",
      venueHHStartFriday1: "",
      venueHHStartFriday2: "",
      venueHHStartSaturday1: "",
      venueHHStartSaturday2: "",
      venueHHStartSunday1: "",
      venueHHStartSunday2: "",
      venueHHEndMonday1: "",
      venueHHEndMonday2: "",
      venueHHEndTuesday1: "",
      venueHHEndTuesday2: "",
      venueHHEndWednesday1: "",
      venueHHEndWednesday2: "",
      venueHHEndThursday1: "",
      venueHHEndThursday2: "",
      venueHHEndFriday1: "",
      venueHHEndFriday2: "",
      venueHHEndSaturday1: "",
      venueHHEndSaturday2: "",
      venueHHEndSunday1: "",
      venueHHEndSunday2: "",
      venueHHNotes: "Two-for-one cocktails and half-priced draft beers"),
];
