import '../models/listing_card_model.dart';

List<ListingCardClass> listingCardList = <ListingCardClass>[
  ListingCardClass(
      venueName: "The Piano Bar",
      venueArea: "The Strip",
      venueLocation: "Harrah's",
      venueImage: "assets/pianobarharrahs.png",
      venueOpenTime: "11:00",
      venueCloseTime: "03:00",
      venueHHStart: "13:00",
      venueHHEnd: "15:00"),
  ListingCardClass(
      venueName: "JammyLand",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueImage: "assets/jammyland.png",
      venueOpenTime: "14:00",
      venueCloseTime: "04:00",
      venueHHStart: "14:00",
      venueHHEnd: "17:00"),
  ListingCardClass(
      venueName: "The Commonwealth",
      venueArea: "Downtown",
      venueLocation: "Fremont East",
      venueImage: "assets/commonwealth.png",
      venueOpenTime: "12:00",
      venueCloseTime: "02:00",
      venueHHStart: "17:00",
      venueHHEnd: "19:00"),
  ListingCardClass(
      venueName: "Velveteen Rabit",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueImage: "assets/velveteenrabbit.png",
      venueOpenTime: "09:00",
      venueCloseTime: "01:00",
      venueHHStart: "18:00",
      venueHHEnd: "20:00"),
  ListingCardClass(
      venueName: "Miller's Alehouse",
      venueArea: "Town Square",
      venueLocation: "Town Square",
      venueImage: "assets/millersalehouse.png",
      venueOpenTime: "07:00",
      venueCloseTime: "01:00",
      venueHHStart: "18:00",
      venueHHEnd: "20:00"),
  ListingCardClass(
      venueName: "Frankie's Tiki Room",
      venueArea: "West of Strip",
      venueLocation: "W Charlston Blv",
      venueImage: "assets/frankiestikiroom.png",
      venueOpenTime: "16:00",
      venueCloseTime: "02:00",
      venueHHStart: "16:00",
      venueHHEnd: "19:00"),
  ListingCardClass(
      venueName: "The Nerd Bar",
      venueArea: "Downtown",
      venueLocation: "Fremont East",
      venueImage: "assets/nerdbar.png",
      venueOpenTime: "14:00",
      venueCloseTime: "01:00",
      venueHHStart: "16:00",
      venueHHEnd: "18:00"),
  ListingCardClass(
      venueName: "The Barbershop",
      venueArea: "The Strip",
      venueLocation: "Cosmopolitan",
      venueImage: "assets/barbershop.png",
      venueOpenTime: "15:00",
      venueCloseTime: "02:00",
      venueHHStart: "15:00",
      venueHHEnd: "18:00"),
  ListingCardClass(
      venueName: "Winchell's Pub & Grill",
      venueArea: "South of Strip",
      venueLocation: "E Warm Springs Rd",
      venueImage: "assets/winchellspubandgrill.png",
      venueOpenTime: "00:00",
      venueCloseTime: "00:00",
      venueHHStart: "",
      venueHHEnd: ""),
  ListingCardClass(
      venueName: "The Front Yard",
      venueArea: "East of Strip",
      venueLocation: "Ellis Island",
      venueImage: "assets/frontyard.png",
      venueOpenTime: "00:00",
      venueCloseTime: "00:00",
      venueHHStart: "",
      venueHHEnd: ""),
  ListingCardClass(
      venueName: "ReBar",
      venueArea: "The Arts District",
      venueLocation: "Arts District",
      venueImage: "assets/rebar.png",
      venueOpenTime: "10:00",
      venueCloseTime: "00:00",
      venueHHStart: "",
      venueHHEnd: ""),
  ListingCardClass(
      venueName: "Pin-ups Bar",
      venueArea: "North of Strip",
      venueLocation: "Cannery Casino",
      venueImage: "assets/rebar.png",
      venueOpenTime: "00:00",
      venueCloseTime: "00:00",
      venueHHStart: "03:00",
      venueHHEnd: "08:00"),
];
