import '../models/listing_card_model.dart';

// This temporary list provides the data required to populate the cards for the
// listings screen.  For testing purposes only.
// Remove once data is fed from Firestore
List<ListingCardClass> listingCardList = <ListingCardClass>[
  ListingCardClass(
    venueID: "LV0001",
    venueName: "The Piano Bar",
    venueArea: "The Strip",
    venueLocation: "Harrah's",
    venueImage: "assets/pianobarharrahs.png",
    venueRegPrice: 3,
    venueHHPrice: 2,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "18:00",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "18:00",
    venueCloseMonday1: "15:00",
    venueCloseMonday2: "02:00",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "15:00",
    venueCloseSunday2: "02:00",
    venueHHStartMonday1: "00:00",
    venueHHStartMonday2: "17:00",
    venueHHStartTuesday1: "01:00",
    venueHHStartTuesday2: "13:00",
    venueHHStartWednesday1: "02:00",
    venueHHStartWednesday2: "14:00",
    venueHHStartThursday1: "03:00",
    venueHHStartThursday2: "15:00",
    venueHHStartFriday1: "04:00",
    venueHHStartFriday2: "16:00",
    venueHHStartSaturday1: "05:00",
    venueHHStartSaturday2: "17:00",
    venueHHStartSunday1: "06:00",
    venueHHStartSunday2: "18:00",
    venueHHEndMonday1: "02:00",
    venueHHEndMonday2: "16:00",
    venueHHEndTuesday1: "03:00",
    venueHHEndTuesday2: "19:00",
    venueHHEndWednesday1: "04:00",
    venueHHEndWednesday2: "20:00",
    venueHHEndThursday1: "05:00",
    venueHHEndThursday2: "21:00",
    venueHHEndFriday1: "06:00",
    venueHHEndFriday2: "22:00",
    venueHHEndSaturday1: "07:00",
    venueHHEndSaturday2: "23:00",
    venueHHEndSunday1: "08:00",
    venueHHEndSunday2: "02:00",
  ),
  ListingCardClass(
    venueID: "LV0002",
    venueName: "JammyLand",
    venueArea: "The Arts District",
    venueLocation: "Arts District",
    venueImage: "assets/jammyland.png",
    venueRegPrice: 2,
    venueHHPrice: 1,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "00:00",
    venueHHStartMonday2: "17:00",
    venueHHStartTuesday1: "01:00",
    venueHHStartTuesday2: "13:00",
    venueHHStartWednesday1: "02:00",
    venueHHStartWednesday2: "14:00",
    venueHHStartThursday1: "03:00",
    venueHHStartThursday2: "15:00",
    venueHHStartFriday1: "04:00",
    venueHHStartFriday2: "16:00",
    venueHHStartSaturday1: "05:00",
    venueHHStartSaturday2: "17:00",
    venueHHStartSunday1: "06:00",
    venueHHStartSunday2: "18:00",
    venueHHEndMonday1: "02:00",
    venueHHEndMonday2: "16:00",
    venueHHEndTuesday1: "03:00",
    venueHHEndTuesday2: "19:00",
    venueHHEndWednesday1: "04:00",
    venueHHEndWednesday2: "20:00",
    venueHHEndThursday1: "05:00",
    venueHHEndThursday2: "21:00",
    venueHHEndFriday1: "06:00",
    venueHHEndFriday2: "22:00",
    venueHHEndSaturday1: "07:00",
    venueHHEndSaturday2: "23:00",
    venueHHEndSunday1: "08:00",
    venueHHEndSunday2: "02:00",
  ),
  ListingCardClass(
    venueID: "LV0003",
    venueName: "The Commonwealth",
    venueArea: "Downtown",
    venueLocation: "Fremont East",
    venueImage: "assets/commonwealth.png",
    venueRegPrice: 2,
    venueHHPrice: 3,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "00:00",
    venueHHStartMonday2: "17:00",
    venueHHStartTuesday1: "01:00",
    venueHHStartTuesday2: "13:00",
    venueHHStartWednesday1: "02:00",
    venueHHStartWednesday2: "14:00",
    venueHHStartThursday1: "03:00",
    venueHHStartThursday2: "15:00",
    venueHHStartFriday1: "04:00",
    venueHHStartFriday2: "16:00",
    venueHHStartSaturday1: "05:00",
    venueHHStartSaturday2: "17:00",
    venueHHStartSunday1: "06:00",
    venueHHStartSunday2: "18:00",
    venueHHEndMonday1: "02:00",
    venueHHEndMonday2: "16:00",
    venueHHEndTuesday1: "03:00",
    venueHHEndTuesday2: "19:00",
    venueHHEndWednesday1: "04:00",
    venueHHEndWednesday2: "20:00",
    venueHHEndThursday1: "05:00",
    venueHHEndThursday2: "21:00",
    venueHHEndFriday1: "06:00",
    venueHHEndFriday2: "22:00",
    venueHHEndSaturday1: "07:00",
    venueHHEndSaturday2: "23:00",
    venueHHEndSunday1: "08:00",
    venueHHEndSunday2: "02:00",
  ),
  ListingCardClass(
    venueID: "LV0004",
    venueName: "Velveteen Rabit",
    venueArea: "The Arts District",
    venueLocation: "Arts District",
    venueImage: "assets/velveteenrabbit.png",
    venueRegPrice: 3,
    venueHHPrice: 3,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0005",
    venueName: "Miller's Alehouse",
    venueArea: "Town Square",
    venueLocation: "Town Square",
    venueImage: "assets/millersalehouse.png",
    venueRegPrice: 2,
    venueHHPrice: 2,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0006",
    venueName: "Frankie's Tiki Room",
    venueArea: "West of Strip",
    venueLocation: "W Charlston Blv",
    venueImage: "assets/frankiestikiroom.png",
    venueRegPrice: 3,
    venueHHPrice: 2,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0007",
    venueName: "The Nerd Bar",
    venueArea: "Downtown",
    venueLocation: "Fremont East",
    venueImage: "assets/nerdbar.png",
    venueRegPrice: 3,
    venueHHPrice: 1,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0008",
    venueName: "The Barbershop",
    venueArea: "The Strip",
    venueLocation: "Cosmopolitan",
    venueImage: "assets/barbershop.png",
    venueRegPrice: 4,
    venueHHPrice: 3,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0009",
    venueName: "Winchell's Pub & Grill",
    venueArea: "South of Strip",
    venueLocation: "E Warm Springs Rd",
    venueImage: "assets/winchellspubandgrill.png",
    venueRegPrice: 2,
    venueHHPrice: 1,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0010",
    venueName: "The Front Yard",
    venueArea: "East of Strip",
    venueLocation: "Ellis Island",
    venueImage: "assets/frontyard.png",
    venueRegPrice: 1,
    venueHHPrice: 1,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0011",
    venueName: "ReBar",
    venueArea: "The Arts District",
    venueLocation: "Arts District",
    venueImage: "assets/rebar.png",
    venueRegPrice: 4,
    venueHHPrice: 2,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
  ListingCardClass(
    venueID: "LV0012",
    venueName: "Pin-ups Bar",
    venueArea: "North of Strip",
    venueLocation: "Cannery Casino",
    venueImage: "assets/pinups.png",
    venueRegPrice: 4,
    venueHHPrice: 3,
    venueInOut: "1",
    venueFood: "3",
    venueSmoking: "1",
    venueRecMusic: "1",
    venueLiveEnt: "1",
    venueCCharge: "1",
    venueDressCode: "1",
    venueChildPolicy: "3",
    venueAccessibility: "2",
    venueDistance: "0.43",
    venueGoodFor1: "Party vibe",
    venueGoodFor2: "All ages over 21",
    venueGoodFor3: "Duelling pianos show",
    venueGoodFor4: "Karaoke early evening",
    venueGoodFor5: "Meeting new people",
    venueGoodFor6: "123456789101112131415161718192021222324252627282930",
    venueOpenMonday1: "11:00",
    venueOpenMonday2: "",
    venueOpenTuesday1: "11:00",
    venueOpenTuesday2: "",
    venueOpenWednesday1: "11:00",
    venueOpenWednesday2: "",
    venueOpenThursday1: "11:00",
    venueOpenThursday2: "",
    venueOpenFriday1: "10:00",
    venueOpenFriday2: "",
    venueOpenSaturday1: "10:00",
    venueOpenSaturday2: "",
    venueOpenSunday1: "10:00",
    venueOpenSunday2: "",
    venueCloseMonday1: "02:00",
    venueCloseMonday2: "",
    venueCloseTuesday1: "02:00",
    venueCloseTuesday2: "",
    venueCloseWednesday1: "02:00",
    venueCloseWednesday2: "",
    venueCloseThursday1: "03:00",
    venueCloseThursday2: "",
    venueCloseFriday1: "03:00",
    venueCloseFriday2: "",
    venueCloseSaturday1: "03:00",
    venueCloseSaturday2: "",
    venueCloseSunday1: "02:00",
    venueCloseSunday2: "",
    venueHHStartMonday1: "",
    venueHHStartMonday2: "",
    venueHHStartTuesday1: "",
    venueHHStartTuesday2: "",
    venueHHStartWednesday1: "",
    venueHHStartWednesday2: "",
    venueHHStartThursday1: "",
    venueHHStartThursday2: "",
    venueHHStartFriday1: "",
    venueHHStartFriday2: "",
    venueHHStartSaturday1: "",
    venueHHStartSaturday2: "",
    venueHHStartSunday1: "",
    venueHHStartSunday2: "",
    venueHHEndMonday1: "",
    venueHHEndMonday2: "",
    venueHHEndTuesday1: "",
    venueHHEndTuesday2: "",
    venueHHEndWednesday1: "",
    venueHHEndWednesday2: "",
    venueHHEndThursday1: "",
    venueHHEndThursday2: "",
    venueHHEndFriday1: "",
    venueHHEndFriday2: "",
    venueHHEndSaturday1: "",
    venueHHEndSaturday2: "",
    venueHHEndSunday1: "",
    venueHHEndSunday2: "",
  ),
];
